Create ban service
s1m0nWasTaken/CS4337_BigDataProject pull request #13
Opened 2024-10-25 13:50 UTC by AlB1111122

## Summary
https://trello.com/c/1sHzxW4d
create a ban service
create endpoints for:
 - adding a new ban for shops and users
 - getting all bans for a specific shop or user
 - checking which resources needed to be unhidden on their own services and doing it
 - getting all of the bans
 -
## How to verify

`../gradlew build`
`docker build -t banservice .`
`docker compose up`

## Tests

## Related

2024-10-25 13:53 UTC, AlB1111122 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Ban service](https://trello.com/c/1sHzxW4d/18-create-ban-service)

2024-10-26 15:44 UTC, tadhgryan2012 submitted a review, later dismissed
Looks good!

2024-11-01 11:16 UTC, tadhgryan2012 submitted a review, later dismissed
lgtm

2024-11-05 16:33 UTC, oOoOoOo0o submitted a review, later dismissed
Very good work.
I Tested every endpoint and almost everything works, a few minor changes needed.
And of course when environment variables are merged in that will be configured so as to prevent using the same port twice in the case of the db.

2024-11-09 08:47 UTC, oOoOoOo0o requested changes

2024-11-09 08:47 UTC, oOoOoOo0o commented on BanService/build.gradle
> +}
Need to add cloud starter config
```
implementation 'org.springframework.cloud:spring-cloud-starter-config'
```

2024-11-09 08:47 UTC, oOoOoOo0o commented on BanService/build.gradle
> +
And add
```
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.3"
    }
}
```

2024-11-09 08:47 UTC, oOoOoOo0o commented on BanService/src/main/java/CS4337/Project/BanService.java
> +  private String shopServiceUrl = "http://shop-service:8080/shopItem/ban/{id}";
This endpoint doesn't exist in shop service, maybe we can add it in this PR, here is an example:
```java
  @PutMapping("shopItem/ban/{id}")
  public ResponseEntity<Map<String, Object>> banShopItem(
      @PathVariable("id") int id, @RequestBody Map<String, String> requestBody) {
    try {
      String hiddenStr = requestBody.get("isHidden");
      Boolean hidden = (hiddenStr == "true" ? true : false);
      String banStatement = "UPDATE `ShopItem` SET isHidden = ? WHERE id = ?";
      jdbcTemplate.update(banStatement, hidden, id);
      return ResponseEntity.ok(Map.of("Shop item banned", hidden));
    } catch (DataAccessException e) {
      return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Map.of("error", e.getMessage()));
    }
  }
  ```

2024-11-10 14:57 UTC, AlB1111122 commented
![](https://github.trello.services/images/mini-trello-icon.png) [set up calls from banservice to other services](https://trello.com/c/sSMWA65p/23-set-up-calls-from-banservice-to-other-services)

2024-11-11 19:42 UTC, oOoOoOo0o approved these changes

2024-11-12 12:45 UTC, tadhgryan2012 approved these changes
LGTM

2024-11-12 13:21 UTC, tadhgryan2012 approved these changes
Please merge

2024-11-12 13:25 UTC, merged