Add Payment Service
s1m0nWasTaken/CS4337_BigDataProject pull request #18
Opened 2024-11-12 02:35 UTC by Maple5201

## Summary
Add Payment Service with auth shop and user service

## How to verify

## Tests

## Related

2024-11-12 12:39 UTC, tadhgryan2012 requested changes
Overall good work, few changes are needed to align with the overall project structure.
Have not checked the endpoints yet but will do once these changes have been made.

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/Dockerfile
We are using java 21

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/HELP.md
This does not need to be commited

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/build.gradle
Need to add spotless for linting

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/docker-compose.yml
The ports can be injected from the config service.

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/gradle/wrapper/gradle-wrapper.jar
Does not need to be commited

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/gradle/wrapper/gradle-wrapper.properties
Does not need to be comitted

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/gradlew
Does not need to be committed.

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/gradlew.bat
Does not need to be committed.

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/settings.gradle
Does not need to be committed.
But should add this service to the root settings.gradle

2024-11-12 12:39 UTC, tadhgryan2012 commented on PaymentService/PaymentService/src/main/init.sql
Some of these tables to made in other services. Please read the other services up and ping these services if you need this data for your service.

2024-11-15 13:01 UTC, tadhgryan2012 approved these changes

2024-11-15 13:21 UTC, Niomahony approved these changes
Possibly the greatest PR of all time

2024-11-15 13:24 UTC, tadhgryan2012 approved these changes
lgtm :D

2024-11-15 13:24 UTC, merged