Ceate account service CRUD and ban endpoint
s1m0nWasTaken/CS4337_BigDataProject pull request #5
Opened 2024-10-17 20:15 UTC by AlB1111122

## Summary
https://trello.com/c/dXJuOhr8
 - create user service module in the java project
 - modify structure to allow it to be made up of multipule modules
 - add create, update, and delete endpoints
 - add a ban endpoint

## How to verify
./gradlew build
docker build -t springbootdemo . (build the project aplication in that was already there)
docker build -t userservice UserService  (build the userservice)
test out the endpoints

2024-10-20 14:09 UTC, oOoOoOo0o requested changes
Only small things, looks good otherwise

2024-10-20 14:09 UTC, oOoOoOo0o commented on UserService/src/main/java/CS4337/Project/User.java
> +  public String getAdress() {
Small typo here, same with setAdress

2024-10-20 14:09 UTC, oOoOoOo0o commented on UserService/src/main/java/CS4337/Project/UserService.java
> +  // @Autowired private SimpleJdbcInsert insert;
Should this comment be removed?

2024-10-20 14:09 UTC, oOoOoOo0o commented on UserService/src/main/java/CS4337/Project/UserService.java
> +  public Map<String, Object> sayhello() {
Is this endpoint necessary?

2024-10-20 14:09 UTC, oOoOoOo0o commented on UserService/src/main/java/CS4337/Project/UserService.java
> +      return ResponseEntity.ok(Map.of("sucess", String.valueOf(updatedRows)));
Typo in "sucess", should be success

2024-10-22 08:09 UTC, oOoOoOo0o approved these changes

2024-10-22 12:05 UTC, tadhgryan2012 approved these changes
Looks good to me!

2024-10-22 12:06 UTC, s1m0nWasTaken approved these changes
Looks good , thanks.

2024-10-22 12:06 UTC, merged

2024-10-25 13:53 UTC, AlB1111122 commented
![](https://github.trello.services/images/mini-trello-icon.png) [create account service](https://trello.com/c/dXJuOhr8/16-create-account-service)